// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOTzQeNZ_9RaakIx9C8Dv2GHFDBRtcd64',
    appId: '1:637570426135:web:b5f044a091f07f68e2c352',
    messagingSenderId: '637570426135',
    projectId: 'musicapp-a8e99',
    authDomain: 'musicapp-a8e99.firebaseapp.com',
    storageBucket: 'musicapp-a8e99.appspot.com',
    measurementId: 'G-PM7M39V2MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiH9fUJvKdek69CzhIjAW1azw-X6WpaPo',
    appId: '1:637570426135:android:3584371d63438ccce2c352',
    messagingSenderId: '637570426135',
    projectId: 'musicapp-a8e99',
    storageBucket: 'musicapp-a8e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2yJDLGAPdYD2b0-4M7CkYDDzm7kMaUU',
    appId: '1:637570426135:ios:29a37485a64e16dce2c352',
    messagingSenderId: '637570426135',
    projectId: 'musicapp-a8e99',
    storageBucket: 'musicapp-a8e99.appspot.com',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2yJDLGAPdYD2b0-4M7CkYDDzm7kMaUU',
    appId: '1:637570426135:ios:29a37485a64e16dce2c352',
    messagingSenderId: '637570426135',
    projectId: 'musicapp-a8e99',
    storageBucket: 'musicapp-a8e99.appspot.com',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOTzQeNZ_9RaakIx9C8Dv2GHFDBRtcd64',
    appId: '1:637570426135:web:e43ebf49a32d32b5e2c352',
    messagingSenderId: '637570426135',
    projectId: 'musicapp-a8e99',
    authDomain: 'musicapp-a8e99.firebaseapp.com',
    storageBucket: 'musicapp-a8e99.appspot.com',
    measurementId: 'G-77227BMC0X',
  );

}